// Generated by CoffeeScript 2.6.1
(function() {
  var Games, Nono;

  Nono = require('./Nono');

  Games = class Games {
    constructor() {
      this.brain = new Nono();
      this.saveNeeded = false;
      this.games = {}; // keyed by owner
      this.load();
    }

    saveIfNeeded() {
      if (!this.saveNeeded) {
        return;
      }
      return this.save();
    }

    load() {}

    save() {}

    updateView(view) {
      var game;
      game = this.games[view.owner];
      if (game == null) {
        // Initialize a fresh game for this new logged-in player
        game = this.brain.newGame(view.owner);
        this.games[view.owner] = game;
      }
      view.game = game;
      this.brain.update(game, view);
    }

    action(view, pid, pkt) {
      if (pkt.action == null) {
        return;
      }
      this.updateView(view);
      return this.brain.action(view.game, pid, pkt);
    }

  };

  module.exports = Games;

}).call(this);
